config/routes.rb
Rails.application.routes.draw do
  root controller: :articles, action: :index
  resources :articles, only: [:show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates_presence_of :title, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :notice, :success, :error
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    if 
    article_params[:title].empty?
    redirect_to new_article_path, notice: 'Please supply a title'
    elsif  
    article_params[:content].empty?
    redirect_to root_path, notice: 'Have a look at some current articles if you need inspiration!'
    else  
    redirect_to root_path, notice: 'Article was successfully created'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    if
      article_params[:title].empty?
      redirect_to edit_article_path, notice: 'Don\'t forget the title!'
    elsif  
      article_params[:content].empty?
      redirect_to edit_article_path, notice: 'If you want to delete this article, click on \'Delete Article\''
    else
      redirect_to @article, notice: 'Article was successfully updated'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :notice then 'alert alert-success'
      when :info then 'alert alert-info'
      when :alert then 'alert alert-danger'
      when :warning then 'alert alert-warning'
    end
  end
  def active_page(active_page)
    @active == active_page ? 'active' : ''
  end
end

app/views/articles/create.html.erb
<h1> Create Article </h1>
<%= form_with scope: article, local: true do |form| %>
    <p>
        <%= form.lable :title %><br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :content %><br>
        <%= form.text_area :content %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<% flash.each do |key, value| %>
  <div class="text-center <%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

<%= form_with model: @article, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :content %>
  <%= form.text_field :content%>
  <%= form.submit 'Update Article' %>
<% end %>

app/views/articles/index.html.erb
<h1>CraftyNews</h1>

<% flash.each do |key, value| %>
  <div class="text-center <%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

  <% @articles.each do |article| %>
    <%= link_to article.title, article_path(article) %><br/>
  <% end %>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<% flash.each do |key, value| %>
  <div class="text-center <%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

<h1> Create Article </h1> 

<%= form_with model: @article, local: true do |form| %>
  <%= form.label :title %><br/>
  <%= form.text_field :title %><br>
  <%= form.label :content %><br/>
  <%= form.text_area :content %><br>
  <%= form.submit 'Create Article' %>
<% end %>

app/views/articles/show.html.erb
<% flash.each do |key, value| %>
  <div class="text-center <%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

<h1><%= @article.title %></h1><br/>
<p><%= @article.content %></p>

<%= link_to 'Edit this Article', edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>